version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DATABASE_URL=postgres://ayan:pgsql123@db:5432/postgres?sslmode=disable
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ayan
      - POSTGRES_PASSWORD=pgsql123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge