definitions:
  api.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  api.FullScrapeRequest:
    properties:
      concurrency:
        type: integer
      maxDepth:
        type: integer
      maxUrls:
        type: integer
      rootUrl:
        type: string
      webhookUrl:
        type: string
    required:
    - rootUrl
    type: object
  api.FullScrapeResponse:
    properties:
      concurrency:
        type: integer
      job_id:
        type: string
      max_urls:
        type: integer
      root_url:
        type: string
      status:
        type: string
    type: object
  api.ScrapeResponse:
    properties:
      output_file:
        type: string
      status:
        type: string
      url:
        type: string
    type: object
  api.SingleScrapeRequest:
    properties:
      url:
        type: string
      webhookUrl:
        type: string
    required:
    - url
    type: object
  models.APIKey:
    properties:
      created_at:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      last_used_at:
        type: string
      name:
        type: string
      user_id:
        type: string
      value:
        type: string
    type: object
  models.AuthResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.ScrappedUrl:
    properties:
      job_id:
        type: string
      scrapped_urls:
        items:
          type: string
        type: array
      status:
        type: string
    type: object
  models.SignupRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /api-key:
    post:
      consumes:
      - application/json
      description: Generates a new API key for the user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIKey'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Generate API key
      tags:
      - API Keys
  /api-keys:
    get:
      consumes:
      - application/json
      description: Retrieves all API keys for the user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.APIKey'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get API keys
      tags:
      - API Keys
  /api/login:
    post:
      consumes:
      - application/json
      description: Authenticate existing user
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: User login
      tags:
      - auth
  /api/signup:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Signup credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: User signup
      tags:
      - auth
  /scrape:
    post:
      consumes:
      - application/json
      description: Scrapes a single URL and converts its content to markdown
      parameters:
      - description: Scrape request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.SingleScrapeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ScrapeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Scrape single URL
      tags:
      - scraping
  /scrape/full:
    post:
      consumes:
      - application/json
      description: Scrapes a website recursively starting from a root URL
      parameters:
      - description: Full scrape request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.FullScrapeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.FullScrapeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Scrape full website
      tags:
      - scraping
  /scrape/status:
    get:
      consumes:
      - application/json
      description: Retrieves the current status of a scraping job
      parameters:
      - description: Job ID
        format: uuid
        in: query
        name: jobId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ScrappedUrl'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get job status
      tags:
      - Jobs
swagger: "2.0"
